"""phase5 vacation bonus field

Revision ID: 7c14438e90ec
Revises: e60184e95d18
Create Date: 2026-08-09 10:47:22.638545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c14438e90ec'
down_revision = 'e60184e95d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'leave_requests',
        sa.Column('bonus_requested', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('leave_requests', 'bonus_requested', server_default=None)
    # fk_org_units_head_user_id уже существует — autogenerate ошибочно
    # определяет use_alter FK как отсутствующий (см. предыдущие миграции).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'bonus_requested')
    # ### end Alembic commands ###
