"""phase3 sync tables

Revision ID: 95112819d421
Revises: caa84ca5a8f5
Create Date: 2026-08-08 13:16:29.561355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95112819d421'
down_revision = 'caa84ca5a8f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_id_mappings',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('external_system', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("entity_type IN ('org_unit', 'user')", name='ck_ext_map_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'external_system', 'external_id', name='uq_ext_map_identity')
    )
    op.create_table('sync_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'failed', 'partial')", name='ck_sync_runs_status'),
    sa.CheckConstraint("trigger_type IN ('scheduled', 'manual')", name='ck_sync_runs_trigger_type'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_change_log',
    sa.Column('sync_run_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('internal_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("change_type IN ('created', 'updated', 'deactivated', 'unchanged')", name='ck_sync_change_log_change_type'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Примечание: fk_org_units_head_user_id уже существует — autogenerate
    # ошибочно определяет use_alter FK как отсутствующий (см. предыдущие миграции).


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_change_log')
    op.drop_table('sync_runs')
    op.drop_table('external_id_mappings')
    # ### end Alembic commands ###
