"""phase5 submission grouping

Revision ID: c16c9d1a2e9a
Revises: 7c14438e90ec
Create Date: 2026-08-09 12:31:44.891044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16c9d1a2e9a'
down_revision = '7c14438e90ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('submission_id', sa.UUID(), nullable=True))
    # fk_org_units_head_user_id уже существует — autogenerate ошибочно
    # определяет use_alter FK как отсутствующий (см. предыдущие миграции).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_org_units_head_user_id', 'org_units', type_='foreignkey')
    op.drop_column('leave_requests', 'submission_id')
    # ### end Alembic commands ###
