"""phase2 blocked periods

Revision ID: caa84ca5a8f5
Revises: 6801c8c68cf0
Create Date: 2026-08-08 07:07:26.305625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa84ca5a8f5'
down_revision = '6801c8c68cf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_periods',
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(scope = 'global' AND org_unit_id IS NULL AND user_id IS NULL) OR (scope = 'org_unit' AND org_unit_id IS NOT NULL AND user_id IS NULL) OR (scope = 'user' AND user_id IS NOT NULL AND org_unit_id IS NULL)", name='ck_blocked_periods_scope_consistency'),
    sa.CheckConstraint("scope IN ('global', 'org_unit', 'user')", name='ck_blocked_periods_scope'),
    sa.CheckConstraint('date_to >= date_from', name='ck_blocked_periods_date_order'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Примечание: fk_org_units_head_user_id уже существует (см. предыдущие миграции) —
    # autogenerate ошибочно определяет use_alter FK как отсутствующий.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_periods')
    # ### end Alembic commands ###
